### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by theetherGit**
Just found a typo 😅😅

### CODE REVIEW

**Comment by nishasen** [comment]
@theetherGit thank you for correcting

**Comment by theetherGit** [comment]
Happy to help 😸. I came to ask for help for making a svelte component Library. You can contact me on twitter.

**Comment by nishasen** [comment]
> Happy to help 😸. I came to ask for help for making a svelte component Library. You can contact me on twitter.

Can you send me your username please of twitter, could not find you

**Comment by nishasen** [comment]
@nisha_sen98 this is my username can you drop a message on twitter

**Comment by theetherGit** [comment]
> > Happy to help 😸. I came to ask for help for making a svelte component Library. You can contact me on twitter.
> 
> Can you send me your username please of twitter, could not find you

@theether0

**Pull request merged**
